/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface MtBackground {
    }
    interface MtCol {
        "breakpoint": string;
    }
    interface MtColumns {
    }
    interface MtContainer {
    }
    interface MtContent {
    }
    interface MtFloated {
    }
    interface MtFooter {
    }
    interface MtList {
    }
    interface MtPage {
    }
    interface MtParagrafo {
    }
    interface MtQuadro01 {
    }
    interface MtQuadro02 {
    }
    interface MtQuadroPictograma01 {
    }
    interface MtRow {
    }
    interface MtTituloH1 {
    }
    interface MtTituloH2 {
    }
    interface MtTituloH3 {
    }
    interface MtTituloH5 {
    }
    interface MtTituloResumo {
    }
}
declare global {
    interface HTMLMtBackgroundElement extends Components.MtBackground, HTMLStencilElement {
    }
    var HTMLMtBackgroundElement: {
        prototype: HTMLMtBackgroundElement;
        new (): HTMLMtBackgroundElement;
    };
    interface HTMLMtColElement extends Components.MtCol, HTMLStencilElement {
    }
    var HTMLMtColElement: {
        prototype: HTMLMtColElement;
        new (): HTMLMtColElement;
    };
    interface HTMLMtColumnsElement extends Components.MtColumns, HTMLStencilElement {
    }
    var HTMLMtColumnsElement: {
        prototype: HTMLMtColumnsElement;
        new (): HTMLMtColumnsElement;
    };
    interface HTMLMtContainerElement extends Components.MtContainer, HTMLStencilElement {
    }
    var HTMLMtContainerElement: {
        prototype: HTMLMtContainerElement;
        new (): HTMLMtContainerElement;
    };
    interface HTMLMtContentElement extends Components.MtContent, HTMLStencilElement {
    }
    var HTMLMtContentElement: {
        prototype: HTMLMtContentElement;
        new (): HTMLMtContentElement;
    };
    interface HTMLMtFloatedElement extends Components.MtFloated, HTMLStencilElement {
    }
    var HTMLMtFloatedElement: {
        prototype: HTMLMtFloatedElement;
        new (): HTMLMtFloatedElement;
    };
    interface HTMLMtFooterElement extends Components.MtFooter, HTMLStencilElement {
    }
    var HTMLMtFooterElement: {
        prototype: HTMLMtFooterElement;
        new (): HTMLMtFooterElement;
    };
    interface HTMLMtListElement extends Components.MtList, HTMLStencilElement {
    }
    var HTMLMtListElement: {
        prototype: HTMLMtListElement;
        new (): HTMLMtListElement;
    };
    interface HTMLMtPageElement extends Components.MtPage, HTMLStencilElement {
    }
    var HTMLMtPageElement: {
        prototype: HTMLMtPageElement;
        new (): HTMLMtPageElement;
    };
    interface HTMLMtParagrafoElement extends Components.MtParagrafo, HTMLStencilElement {
    }
    var HTMLMtParagrafoElement: {
        prototype: HTMLMtParagrafoElement;
        new (): HTMLMtParagrafoElement;
    };
    interface HTMLMtQuadro01Element extends Components.MtQuadro01, HTMLStencilElement {
    }
    var HTMLMtQuadro01Element: {
        prototype: HTMLMtQuadro01Element;
        new (): HTMLMtQuadro01Element;
    };
    interface HTMLMtQuadro02Element extends Components.MtQuadro02, HTMLStencilElement {
    }
    var HTMLMtQuadro02Element: {
        prototype: HTMLMtQuadro02Element;
        new (): HTMLMtQuadro02Element;
    };
    interface HTMLMtQuadroPictograma01Element extends Components.MtQuadroPictograma01, HTMLStencilElement {
    }
    var HTMLMtQuadroPictograma01Element: {
        prototype: HTMLMtQuadroPictograma01Element;
        new (): HTMLMtQuadroPictograma01Element;
    };
    interface HTMLMtRowElement extends Components.MtRow, HTMLStencilElement {
    }
    var HTMLMtRowElement: {
        prototype: HTMLMtRowElement;
        new (): HTMLMtRowElement;
    };
    interface HTMLMtTituloH1Element extends Components.MtTituloH1, HTMLStencilElement {
    }
    var HTMLMtTituloH1Element: {
        prototype: HTMLMtTituloH1Element;
        new (): HTMLMtTituloH1Element;
    };
    interface HTMLMtTituloH2Element extends Components.MtTituloH2, HTMLStencilElement {
    }
    var HTMLMtTituloH2Element: {
        prototype: HTMLMtTituloH2Element;
        new (): HTMLMtTituloH2Element;
    };
    interface HTMLMtTituloH3Element extends Components.MtTituloH3, HTMLStencilElement {
    }
    var HTMLMtTituloH3Element: {
        prototype: HTMLMtTituloH3Element;
        new (): HTMLMtTituloH3Element;
    };
    interface HTMLMtTituloH5Element extends Components.MtTituloH5, HTMLStencilElement {
    }
    var HTMLMtTituloH5Element: {
        prototype: HTMLMtTituloH5Element;
        new (): HTMLMtTituloH5Element;
    };
    interface HTMLMtTituloResumoElement extends Components.MtTituloResumo, HTMLStencilElement {
    }
    var HTMLMtTituloResumoElement: {
        prototype: HTMLMtTituloResumoElement;
        new (): HTMLMtTituloResumoElement;
    };
    interface HTMLElementTagNameMap {
        "mt-background": HTMLMtBackgroundElement;
        "mt-col": HTMLMtColElement;
        "mt-columns": HTMLMtColumnsElement;
        "mt-container": HTMLMtContainerElement;
        "mt-content": HTMLMtContentElement;
        "mt-floated": HTMLMtFloatedElement;
        "mt-footer": HTMLMtFooterElement;
        "mt-list": HTMLMtListElement;
        "mt-page": HTMLMtPageElement;
        "mt-paragrafo": HTMLMtParagrafoElement;
        "mt-quadro-01": HTMLMtQuadro01Element;
        "mt-quadro-02": HTMLMtQuadro02Element;
        "mt-quadro-pictograma-01": HTMLMtQuadroPictograma01Element;
        "mt-row": HTMLMtRowElement;
        "mt-titulo-h1": HTMLMtTituloH1Element;
        "mt-titulo-h2": HTMLMtTituloH2Element;
        "mt-titulo-h3": HTMLMtTituloH3Element;
        "mt-titulo-h5": HTMLMtTituloH5Element;
        "mt-titulo-resumo": HTMLMtTituloResumoElement;
    }
}
declare namespace LocalJSX {
    interface MtBackground {
    }
    interface MtCol {
        "breakpoint"?: string;
    }
    interface MtColumns {
    }
    interface MtContainer {
    }
    interface MtContent {
    }
    interface MtFloated {
    }
    interface MtFooter {
    }
    interface MtList {
    }
    interface MtPage {
    }
    interface MtParagrafo {
    }
    interface MtQuadro01 {
    }
    interface MtQuadro02 {
    }
    interface MtQuadroPictograma01 {
    }
    interface MtRow {
    }
    interface MtTituloH1 {
    }
    interface MtTituloH2 {
    }
    interface MtTituloH3 {
    }
    interface MtTituloH5 {
    }
    interface MtTituloResumo {
    }
    interface IntrinsicElements {
        "mt-background": MtBackground;
        "mt-col": MtCol;
        "mt-columns": MtColumns;
        "mt-container": MtContainer;
        "mt-content": MtContent;
        "mt-floated": MtFloated;
        "mt-footer": MtFooter;
        "mt-list": MtList;
        "mt-page": MtPage;
        "mt-paragrafo": MtParagrafo;
        "mt-quadro-01": MtQuadro01;
        "mt-quadro-02": MtQuadro02;
        "mt-quadro-pictograma-01": MtQuadroPictograma01;
        "mt-row": MtRow;
        "mt-titulo-h1": MtTituloH1;
        "mt-titulo-h2": MtTituloH2;
        "mt-titulo-h3": MtTituloH3;
        "mt-titulo-h5": MtTituloH5;
        "mt-titulo-resumo": MtTituloResumo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mt-background": LocalJSX.MtBackground & JSXBase.HTMLAttributes<HTMLMtBackgroundElement>;
            "mt-col": LocalJSX.MtCol & JSXBase.HTMLAttributes<HTMLMtColElement>;
            "mt-columns": LocalJSX.MtColumns & JSXBase.HTMLAttributes<HTMLMtColumnsElement>;
            "mt-container": LocalJSX.MtContainer & JSXBase.HTMLAttributes<HTMLMtContainerElement>;
            "mt-content": LocalJSX.MtContent & JSXBase.HTMLAttributes<HTMLMtContentElement>;
            "mt-floated": LocalJSX.MtFloated & JSXBase.HTMLAttributes<HTMLMtFloatedElement>;
            "mt-footer": LocalJSX.MtFooter & JSXBase.HTMLAttributes<HTMLMtFooterElement>;
            "mt-list": LocalJSX.MtList & JSXBase.HTMLAttributes<HTMLMtListElement>;
            "mt-page": LocalJSX.MtPage & JSXBase.HTMLAttributes<HTMLMtPageElement>;
            "mt-paragrafo": LocalJSX.MtParagrafo & JSXBase.HTMLAttributes<HTMLMtParagrafoElement>;
            "mt-quadro-01": LocalJSX.MtQuadro01 & JSXBase.HTMLAttributes<HTMLMtQuadro01Element>;
            "mt-quadro-02": LocalJSX.MtQuadro02 & JSXBase.HTMLAttributes<HTMLMtQuadro02Element>;
            "mt-quadro-pictograma-01": LocalJSX.MtQuadroPictograma01 & JSXBase.HTMLAttributes<HTMLMtQuadroPictograma01Element>;
            "mt-row": LocalJSX.MtRow & JSXBase.HTMLAttributes<HTMLMtRowElement>;
            "mt-titulo-h1": LocalJSX.MtTituloH1 & JSXBase.HTMLAttributes<HTMLMtTituloH1Element>;
            "mt-titulo-h2": LocalJSX.MtTituloH2 & JSXBase.HTMLAttributes<HTMLMtTituloH2Element>;
            "mt-titulo-h3": LocalJSX.MtTituloH3 & JSXBase.HTMLAttributes<HTMLMtTituloH3Element>;
            "mt-titulo-h5": LocalJSX.MtTituloH5 & JSXBase.HTMLAttributes<HTMLMtTituloH5Element>;
            "mt-titulo-resumo": LocalJSX.MtTituloResumo & JSXBase.HTMLAttributes<HTMLMtTituloResumoElement>;
        }
    }
}
