/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface MtGridRow {
        /**
          * @default 2
         */
        "cols": number;
    }
    interface MtTitleH1 {
        "ano": '202';
        "especialidade": 'car' | 'nef';
        "produto": 'medcurso' | 'med';
    }
}
declare global {
    interface HTMLMtGridRowElement extends Components.MtGridRow, HTMLStencilElement {
    }
    var HTMLMtGridRowElement: {
        prototype: HTMLMtGridRowElement;
        new (): HTMLMtGridRowElement;
    };
    interface HTMLMtTitleH1Element extends Components.MtTitleH1, HTMLStencilElement {
    }
    var HTMLMtTitleH1Element: {
        prototype: HTMLMtTitleH1Element;
        new (): HTMLMtTitleH1Element;
    };
    interface HTMLElementTagNameMap {
        "mt-grid-row": HTMLMtGridRowElement;
        "mt-title-h1": HTMLMtTitleH1Element;
    }
}
declare namespace LocalJSX {
    interface MtGridRow {
        /**
          * @default 2
         */
        "cols"?: number;
    }
    interface MtTitleH1 {
        "ano"?: '202';
        "especialidade"?: 'car' | 'nef';
        "produto"?: 'medcurso' | 'med';
    }
    interface IntrinsicElements {
        "mt-grid-row": MtGridRow;
        "mt-title-h1": MtTitleH1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mt-grid-row": LocalJSX.MtGridRow & JSXBase.HTMLAttributes<HTMLMtGridRowElement>;
            "mt-title-h1": LocalJSX.MtTitleH1 & JSXBase.HTMLAttributes<HTMLMtTitleH1Element>;
        }
    }
}
